name: fisica
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  aligned_dialog: ^0.0.7
  auto_size_text: 3.0.0
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.10
  cloud_firestore_platform_interface: ^6.1.11
  cloud_firestore_web: ^3.10.10
  dropdown_button2: ^2.3.9
  firebase_auth: ^4.18.0
  firebase_auth_platform_interface: ^7.2.0
  firebase_auth_web: ^5.10.1
  firebase_core: ^2.27.2
  firebase_core_platform_interface: ^5.0.0
  firebase_core_web: ^2.13.0
  firebase_admin: ^0.2.0
  floating_bottom_navigation_bar: 1.5.2
  flutter_animate: ^4.5.0
  flutter_cache_manager: ^3.3.1
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  from_css_color: 2.0.0
  go_router: ^13.2.2
  google_fonts: ^4.0.4
  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.1.22
  google_sign_in_ios: ^5.7.5
  google_sign_in_platform_interface: ^2.4.5
  google_sign_in_web: ^0.12.4
  intl: 0.18.1
  json_path: ^0.7.1
  page_transition: ^2.1.0
  path_provider: ^2.1.2
  path_provider_android: ^2.2.2
  path_provider_foundation: ^2.3.2
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8
  provider: ^6.1.2
  rxdart: 0.27.7
  shared_preferences: ^2.2.2
  shared_preferences_android: ^2.2.1
  shared_preferences_platform_interface: ^2.3.2
  shared_preferences_web: ^2.3.0
  sign_in_with_apple: ^6.0.0
  sign_in_with_apple_platform_interface: 1.0.0
  sign_in_with_apple_web: ^2.0.0
  sqflite: ^2.3.2
  stream_transform: 2.1.0
  timeago: ^3.6.1
  url_launcher: ^6.2.5
  url_launcher_android: ^6.3.0
  url_launcher_ios: ^6.2.5
  url_launcher_platform_interface: ^2.3.2
  flutter_keyboard_visibility: ^6.0.0
  http: ^0.13.3
  social_share: ^2.3.1
  pull_to_refresh: ^2.0.0
  flutter_blue_plus: ^1.31.13
  flutter_dash: ^1.0.0
  modal_bottom_sheet: ^3.0.0
  toggle_switch: ^2.1.0
  model_viewer_plus: ^1.7.0
  flutter_launcher_icons: ^0.13.1
  easy_rich_text: ^2.1.0
  fl_chart: ^0.67.0
  bottom_picker:
    git:
      url: https://github.com/juntaenoh/Bottom-Picker.git

  cupertino_icons: ^1.0.0
  firebase_app_check: ^0.2.1+19
  table_calendar: ^3.0.9
  logger: ^2.2.0
  persistent_bottom_nav_bar: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/lottie_animations/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/icons/
    - assets/body3d/
    - assets/bodygrapic/back/female/
    - assets/bodygrapic/back/male/
    - assets/bodygrapic/flat/female/
    - assets/bodygrapic/flat/male/
    - assets/bodygrapic/yo/female/
    - assets/bodygrapic/yo/male/
    - assets/bodygrapic/front/female/
    - assets/bodygrapic/front/male/
    - assets/bodygrapic/left/female/
    - assets/bodygrapic/left/male/
    - assets/bodygrapic/right/female/
    - assets/bodygrapic/right/male/
    - assets/bodygrapic/leftroll/female/
    - assets/bodygrapic/leftroll/male/
    - assets/bodygrapic/rightroll/female/
    - assets/bodygrapic/rightroll/male/
    - assets/bodygrapic/normal/female/
    - assets/bodygrapic/normal/male/
    - assets/text/
  fonts:
    - family: "Pretendard"
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
