// Export pages
export 'views/login/Login_main.dart' show LoginWidget;
export 'views/home/home_page/home_page_view.dart' show HomePageWidget;
export 'views/login/Login_smscode_view.dart' show SmscodeWidget;
export 'views/login/Login_singup_tos_view.dart' show AgreeTosWidget;
export 'views/login/Login_singup_getid_view.dart' show GetidWidget;
export 'views/login/Login_singup_pw_view.dart' show SetPwWidget;
export 'views/login/Login_email_pw_view.dart' show InputPwWidget;
export 'views/login/Login_singup_info_view.dart' show UserInfoWidget;
export 'views/login/ToS.dart' show certifyWidget;
export 'views/login/checkemail.dart' show checkemailWidget;
export 'views/home/group/group.dart' show GroupWidget;
export 'views/home/group/creategroup_widget.dart' show CreategroupWidget;
export 'views/home/plan/plan.dart' show planWidget;
export 'views/home/mypage/mypage_main_view.dart' show MypageWidget;
export 'package:fisica/views/home/group/settings/InvitationHistory_screen.dart' show GroupJoinHistory;
export 'package:fisica/views/home/group/settings/Remove_member_screen.dart' show RemoveMemberPage;
export 'package:fisica/views/home/group/No_group_Screen.dart';
export 'package:fisica/components/cancel_invitation.dart';
export 'package:fisica/views/home/group/Yes_group_Screen.dart';
export 'utils/internationalization.dart';
export 'package:fisica/components/invitation_codeError.dart';
export 'package:fisica/components/Success_Join.dart';
export 'package:fisica/utils/fisica_theme.dart';
export 'package:fisica/service/User_Controller.dart';
export 'package:flutter_localizations/flutter_localizations.dart';
export 'utils/flutter_util.dart';
export 'package:fisica/views/home/group/group_invitation_screen.dart';
export 'package:firebase_app_check/firebase_app_check.dart';
export 'package:flutter_svg/svg.dart';
export 'package:flutter_web_plugins/url_strategy.dart';
export 'package:firebase_core/firebase_core.dart';
export 'package:aligned_dialog/aligned_dialog.dart';
export 'package:fisica/views/login/login_components/Login_Fail.dart';
export 'package:fisica/widgets/custom_input_field_widget.dart';
export 'package:firebase_auth/firebase_auth.dart';
export 'package:fisica/service/group_api.dart';
export 'package:fisica/widgets/App_icon_button.dart';
export 'package:fisica/views/home/group/settings/ChangeGroupName_screen.dart';
export 'package:fisica/views/home/group/settings/DeleteGroup_screen.dart';
export 'package:fisica/views/home/group/settings/GroupHistory_screen.dart';
export 'package:fisica/views/home/group/settings/GroupJoinRequests_screen.dart';
export 'package:fisica/views/home/group/settings/InvitationCodeManage_screen.dart';
export 'package:fisica/views/home/group/settings/LeaveGroup_screen.dart';
export 'package:fisica/views/home/group/settings/MemberManage_screen.dart';
export 'package:fisica/views/home/group/settings/NotificationSetting_screen.dart';
export 'package:fisica/views/home/group/settings/PublicInfoSettings_screen.dart';
export 'package:fisica/views/home/group/join_group.dart';
export 'package:fisica/views/home/group/group_info_screen.dart';
export 'package:flutter_blue_plus/flutter_blue_plus.dart';
export 'dart:async';
export 'dart:io';
export 'package:model_viewer_plus/model_viewer_plus.dart';
export 'package:fisica/view_models/Data_Notifire.dart';
export 'package:fisica/widgets/Loding_button_widget.dart';
export 'package:fisica/utils/internationalization.dart';

String mainurl = 'http://3.37.197.238:8080';
//http://203.232.210.68:8080
String version = '1.0.14';
